stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine/git  # 使用包含 Git 的轻量级镜像
  before_script:
    # 配置 Git 用户信息
    - git config --global user.email "lijiayang@shoplazza.com"
    - git config --global user.name "lijiayang"
  script:
    # 添加 GitHub 仓库为远程地址（使用 HTTPS + Token 认证）
    - git remote add github git@github.com:Camellia-shoplaza/test_repo.git
    # 强制推送到 GitHub（覆盖式同步）
    # - git push github HEAD:master --force
    # 获取当前分支名称
    - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    # 推送到 GitHub 的对应分支
    - git push github HEAD:$CURRENT_BRANCH --force
  rules:
    # 仅在 master 分支触发同步
    - if: $CI_COMMIT_BRANCH