stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  image: alpine:latest
  before_script:
    # 安装 SSH 客户端和 Git
    - apk add --no-cache openssh git
    # 创建 SSH 目录
    - mkdir -p ~/.ssh
    # 设置 SSH 私钥
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # 添加 GitHub 的 SSH 指纹
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # 配置 Git 用户信息
    - git config --global user.email "lijiayang@shoplazza.com"
    - git config --global user.name "Lijiayang"
  script:
    # 添加 GitHub 仓库作为远程仓库
    - git remote add github git@github.com:Camellia-shoplaza/test_repo.git
    - git pull --rebase github master  # 拉取远程仓库最新代码
    - |
      MAX_RETRIES=3
      RETRY_COUNT=0
      while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
        if git push -u github HEAD:refs/heads/master; then
          break
        fi
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep 5
      done
      if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
        echo "推送失败，达到最大重试次数"
        exit 1
      fi
  only:
    - master  # 仅在 master 分支有代码推送时触发此任务