stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  image: alpine:latest
  before_script:
    # 安装 SSH 客户端和 Git
    - apk add --no-cache openssh git
    # 创建 SSH 目录
    - mkdir -p ~/.ssh
    # 设置 SSH 私钥
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # 添加 GitHub 的 SSH 指纹
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # 配置 Git 用户信息
    - git config --global user.email "lijiayang@shoplazza.com"
    - git config --global user.name "lijiayang"
  script:
    # 添加 GitHub 仓库作为远程仓库
    - git remote add github git@github.com:Camellia-shoplaza/test_repo.git
    # 获取当前分支名称
    - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    # 强制推送到 GitHub 的对应分支
    - git push -f github HEAD:$CURRENT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH  # 当有分支提交时触发任务
      when: always